services:
  postgres:
    image: postgres:17.2-alpine3.20
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    tmpfs:
      - /tmp/pids/
    tty: true
    stdin_open: true

volumes:
  postgres: {}
