services:
  postgres:
    image: postgres:15.10-alpine3.21
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env.development
      - .env.docker
    ports:
      - 3000:3000
    volumes:
      - .:/rails
    tmpfs:
      - /tmp/pids/
    tty: true
    stdin_open: true

volumes:
  postgres: {}
