production:
  secret_key_base: static_production_secret_key # Don't use this in real production

development:
  secret_key_base: static_development_secret_key

test:
  secret_key_base: static_test_secret_key
